"""Base classes and data structures for trading strategies."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, Iterable, List


class SignalType(Enum):
    """Enumeration of signal directions."""

    BUY = auto()
    SELL = auto()


@dataclass(frozen=True)
class StrategySignal:
    """A trading signal generated by a strategy."""

    symbol: str
    date: Any
    strategy: str
    signal_type: SignalType
    confidence: float
    metadata: Dict[str, Any] = field(default_factory=dict)


class Strategy:
    """Protocol-like base class for all trading strategies."""

    name: str

    def generate_signals(self, symbol: str, prices: Any) -> List[StrategySignal]:  # pragma: no cover - interface
        """Return a list of signals for the given symbol and price data."""
        raise NotImplementedError

    def required_columns(self) -> Iterable[str]:  # pragma: no cover - interface
        """Columns that must be present in the input price DataFrame."""
        return ("close", "volume")
